spring:
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3307/user_service?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ENV_ROOT_USER}
    password: ${ENV_ROOT_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  threads:
    virtual:
      enabled: true

logging:
  level:
    com.kayky: debug
    org.springframework.security: debug
server:
  port: 8091
  servlet:
    context-path: /

    error:
      include-stacktrace: on_param
      include-binding-errors: always
      include-message: always
    tomcat:
      threads:
        max: 20

brasil-api:
  base-url: ${BRASIL_API_BASE_URL:https://brasilapi.com.br/api}
  cep-uri: ${BRASIL_API_URI:/cep/v1/{cep}}