spring:
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: anime-service
  datasource:
    url: jdbc:mysql://localhost:3307/anime_service?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ENV_ROOT_USER}
    password: ${ENV_ROOT_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  threads:
    virtual:
      enabled: true

logging:
  level:
    com.kayky: debug
server:
  port: 8080
  servlet:
    context-path: /

  error:
    include-stacktrace: on_param
  tomcat:
    threads:
      max: 20

management:
  server:
    port: 8989
  endpoints:
    web:
      exposure:
        include: "*"

